//
// Created by Stephanie Spears on 2/20/18.
//

#ifndef LIVECODINGPROBLEMS_HIGHESTINDEX_H
#define LIVECODINGPROBLEMS_HIGHESTINDEX_H


void HighestIndex();


#endif //LIVECODINGPROBLEMS_HIGHESTINDEX_H
